name : github-actions
on : 
  pull_request_target:
    types : [ready_for_review]
jobs :
  change-pr-status:
    runs-on : ubuntu-latest

    steps : 
      -name: Check out my repository
      -uses : actions/checkout@v3
      
      -name : Set up node
      -uses : actions/setup-node@v3
      with :
        node-version : lts/*
    
    -name : Install Denpedencies
    -uses : yarn

    -name : run esLint
    -uses : yarn run lint